version: '3'
services:
  mq:
    container_name: mq
    image: rabbitmq:3.8-web
    build: .
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./data/mq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15675:15675"
      - "15672:15672"
      - "1883:1883"
